# Generated by Django 3.1.4 on 2021-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
