# Generated by Django 3.1.4 on 2021-01-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
